version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user-name
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cashier
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - /tmp/db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    restart: "always"
    depends_on:
      - db
